# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Workspace/DSD/team_project/HW3/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Workspace/DSD/team_project/HW3/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_verilog -library xil_defaultlib {
  C:/Workspace/DSD/team_project/HW3/project_1/project_1.srcs/sources_1/imports/sources/ss_decoder.v
  C:/Workspace/DSD/team_project/HW3/project_1/project_1.srcs/sources_1/imports/sources/ss_drive.v
  C:/Workspace/DSD/team_project/HW3/project_1/project_1.srcs/sources_1/new/Top_module.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Workspace/DSD/team_project/HW3/project_1/project_1.srcs/constrs_1/imports/constrs/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Workspace/DSD/team_project/HW3/project_1/project_1.srcs/constrs_1/imports/constrs/Nexys4DDR_Master.xdc]


synth_design -top Top_module -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Top_module.dcp

catch { report_utilization -file Top_module_utilization_synth.rpt -pb Top_module_utilization_synth.pb }
